---

- name: detect binary file for glauth-ui
  become: false
  delegate_to: "{{ glauth_ui_delegate_to }}"
  stat:
    path: "{{ glauth_ui_local_tmp_directory }}/glauth-ui"
  register: stat_file_binary

- block:
    - name: propagate glauth binaries
      copy:
        src: "{{ glauth_ui_local_tmp_directory }}/glauth-ui"
        dest: "{{ glauth_ui_install_path }}/glauth-ui"
        mode: 0755
        owner: "{{ glauth_ui_system_user }}"
        group: "{{ glauth_ui_system_group }}"
        remote_src: "{{ 'true' if glauth_ui_direct_download else 'false' }}"

    - name: make files executable
      file:
        path: "{{ glauth_ui_install_path }}/glauth-ui"
        mode: 0755
        owner: "{{ glauth_ui_system_user }}"
        group: "{{ glauth_ui_system_group }}"

  when:
    - stat_file_binary.stat.exists

- name: propagate glauth locales
  block:
    # - name: create locales directory for installed version
    #   file:
    #     state: directory
    #     path: "{{ glauth_ui_install_path }}/plugins"
    #     mode: 0755
    #     owner: "{{ glauth_ui_system_user }}"
    #     group: "{{ glauth_ui_system_group }}"

    - name: copy locales in place
      copy:
        src: "{{ glauth_ui_local_tmp_directory }}/locales"
        dest: "{{ glauth_ui_install_path }}/"
        mode: 0644
        owner: "{{ glauth_ui_system_user }}"
        group: "{{ glauth_ui_system_group }}"
        remote_src: "{{ 'true' if glauth_ui_direct_download else 'false' }}"

- name: create local facts
  template:
    src: ansible_facts.j2
    dest: /etc/ansible/facts.d/glauth-ui.fact
    mode: 0755

# - name: create glauth-ui lib directory
#   file:
#     state: directory
#     path: "{{ glauth_ui_data_dir }}"
#     mode: 0755

- name: create link to binary
  file:
    src: "{{ glauth_ui_install_path }}/glauth-ui"
    dest: "/usr/bin/glauth-ui"
    state: link
    force: true
    follow: false
  notify:
    - restart glauth-ui

- name: systemd
  block:
    - name: create systemd service unit
      template:
        src: "init/systemd/glauth-ui.service.j2"
        dest: "{{ systemd_lib_directory }}/glauth-ui.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload
        - restart glauth-ui

    - name: create glauth-ui run configuration
      template:
        src: "glauth-ui.j2"
        dest: "{{ glauth_ui_defaults_directory }}/glauth-ui"
        force: true
        owner: root
        group: "{{ glauth_ui_system_group }}"
        mode: 0640
      notify:
        - validate config
        - reload glauth-ui
  when:
    - ansible_service_mgr | lower == "systemd"

- name: openrc
  block:
    - name: create openrc service configuration
      template:
        src: "init/openrc/conf.d/glauth-ui.j2"
        dest: "/etc/conf.d/glauth-ui"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init configuration
      template:
        src: "init/openrc/init.d/glauth-ui.j2"
        dest: "/etc/init.d/glauth-ui"
        owner: root
        group: root
        mode: 0750
  when:
    - ansible_service_mgr | lower == "openrc"

...
